# Site settings
title: Mishal Assif P K
email: mishal_assif@iitb.ac.in
description: > # this means to ignore newlines until "baseurl:"
  Final year Dual degree student, Department of Mechanical engineering at IIT-Bombay.. 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://mishalassif.github.io" # the base hostname & protocol for your site
#twitter_username: JAlexBranham
#github_username:  jabranham
#permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
