# Site settings
title: Mishal Assif P K
email: mishal2@illinois.edu
description: > # this means to ignore newlines until "baseurl:"
  Second year Ph.D student, Department of Electrical engineering at UIUC. 
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://mishalassif.github.io" # the base hostname & protocol for your site
#twitter_username: JAlexBranham
#github_username:  jabranham
#permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
