# Site settings
title: Mishal Assif P K
email: msl.asf97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Member of Research Staff, Voleon Group
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://mishalassif.github.io" # the base hostname & protocol for your site
#twitter_username: JAlexBranham
github_username:  Mishalassif
#permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
